cms/urls.py
from django.urls import path

from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    ###試しにBeforeTopViewを実装しました。必要ならすぐ消します
    #path('genuine/', views.TopView.as_view(), name='genuine_top'),
    #path('', views.BeforeTopView, name='top'),
    ###
    path('infomation/', views.InfomationView.as_view(), name='infomation'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('guestdelete/', views.GuestDelete, name='guestdelete'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signupagain/', views.UserCreateAgain.as_view(), name='signupagain'),
    path('guest/', views.GuestCreate.as_view(), name='guest'),
    path('guestagain/', views.GuestCreateAgain.as_view(), name='guestagain'),
    #path('guesttorealuser/', views.GuestToRealUser.as_view(), name='guestupdate'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), #追加
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'), #追加
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    #path('user/', views.UserList.as_view(), name='user_list'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user_delete'),
    #path('user/<int:pk>/recommend/', views.RecommendView.as_view(), name='user_recommend'),
    #path('works/<int:pk>/', views.WorksView.as_view(), name='works'),
    #path('works/', views.WorksList.as_view(), name='works_list'),
]

mkdata/urls.py
from django.urls import path

from . import views

app_name = 'mkdata'
###urls.pyにもapp_nameをつけてる

urlpatterns = [
    #path('<int:pk>/', views.IndexView.as_view(), name='index'),
    path('<int:work_id>/', views.IndexView, name='index'),
    path('<int:work_id>/again/', views.IndexAgainView, name='index_again'),
    path('<int:work_id>/vote/', views.vote, name='vote'),
    #path('selectgenre/', views.SelectGenreView, name='selectgenre'),
    path('startfreevote/', views.StartFreevoteView.as_view(), name='startfreevote'),
    path('mkaddwork/', views.mkaddwork, name='mkaddwork'),
    path('freevote/<int:pk>/', views.AddWorkView.as_view(), name='freevote'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    #path('<int:work_id>/recommend/', views.recommend, name='recommend'),
    path('recommend/', views.recommend, name='recommend'),
    #path('detail/', views.detail,name='detail'),
    path('start/',views.StartView, name='start'),
    path('userread/',views.UserRead, name='userread'),
    path('selectfavorite/', views.SelectFavoriteView, name='selectfavorite'),
    path('selectfavoriteagain/', views.SelectFavoriteAgainView, name='selectfavoriteagain'),
    path('userselected/', views.UserSelected, name='userselected'),
    path('haveread/<int:work_id>/', views.HaveRead, name='haveread'),
    #path('startSurvey/', views.StartSurveyView, name="startSurvey"),
    #path('usersee/', views.UserSee, name='usersee')
    #path('upload/', views.upload, name='upload'),
]

mkdata/forms.py
from typing import Type

from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from mkdata.models import Work, AddedWork

UserModel = get_user_model()

'''
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs['class'] = 'input'
       self.fields['password'].widget.attrs['class'] = 'input'
'''


class CollectDataForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = (
        'like', 'joy', 'anger', 'sadness', 'fun', 'tech_constitution', 'tech_story', 'tech_character', 'tech_speech',
        'tech_picture')

    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['like'].widget.attrs['class'] = 'input'
        self.fields['joy'].widget.attrs['class'] = 'input'
        self.fields['anger'].widget.attrs['class'] = 'input'
        self.fields['sadness'].widget.attrs['class'] = 'input'
        self.fields['fun'].widget.attrs['class'] = 'input'
        self.fields['tech_constitution'].widget.attrs['class'] = 'input'
        self.fields['tech_story'].widget.attrs['class'] = 'input'
        self.fields['tech_character'].widget.attrs['class'] = 'input'
        self.fields['tech_speech'].widget.attrs['class'] = 'input'
        self.fields['tech_picture'].widget.attrs['class'] = 'input'

        ###
        #self.pk = kwargs.pop('pk')
        #super(CollectDataForm, self).__init__(*args, **kwargs)
        #####

    def update_database(self):
        for items in self.fields:
            self.model.like += self.fields['like'].widget.attrs['class']
    '''


class AddWorkForm(forms.ModelForm):
    class Meta:
        model = AddedWork
        fields = ('like', 'joy', 'anger', 'sadness', 'fun', 'tech_constitution', 'tech_story', 'tech_character',
                  'tech_speech', 'tech_picture', 'tech_audio', 'tech_acting')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'


class StartFreevoteForm(forms.ModelForm):
    class Meta:
        model = AddedWork
        fields = ('genre','name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

mkdata/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth import get_user_model
from django.contrib.auth.views import (
    LoginView,
)
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import CreateView

from .forms import CollectDataForm, AddWorkForm, StartFreevoteForm#, SelectGenreForm

from django.shortcuts import resolve_url

from cms.models import User
from cms.mixins import OnlyYouMixin
from .mixins import OnlyRegistererMixin

from .models import Work, AddedWork, try_Work_get

from .recommend import recommendselect, user_standardize

from django.contrib import messages

import csv
from io import TextIOWrapper, StringIO


def IndexView(request, work_id):
    user = request.user

    '''
    # if user.work_read[work_id - 1] != "2":
    if int(user.work_read[work_id - 1]) <= 1:
        return HttpResponseRedirect(reverse('mkdata:index', args=(work_id + 1,)))

    try:
        work = Work.objects.get(pk=work_id)
    except:
        return HttpResponseRedirect(reverse('mkdata:index', args=(work_id + 1,)))
    '''

    work = Work.objects.get(pk=work_id)

    if work.genre is None:
        work.genre = 1
        work.save()

    template = loader.get_template('mkdata/sampleform.html')

    # isLast = (work_id == Work.objects.all().order_by("-id")[0].id)
    isLast = (user.work_read[work_id - 1] == "4")

    context = {
        'work': work,
        'isLast': isLast,
        'user': user,
    }

    return HttpResponse(template.render(context, request))

###入力でエラーが出た時用, 汎用ビューとかをうまく使えば要らなくなるかも
def IndexAgainView(request, work_id):
    user = request.user

    '''
    # if user.work_read[work_id - 1] != "2":
    if int(user.work_read[work_id - 1]) <= 1:
        return HttpResponseRedirect(reverse('mkdata:index', args=(work_id + 1,)))

    try:
        work = Work.objects.get(pk=work_id)
    except:
        return HttpResponseRedirect(reverse('mkdata:index', args=(work_id + 1,)))
    '''

    work = Work.objects.get(pk=work_id)

    template = loader.get_template('mkdata/againform.html')

    # isLast = (work_id == Work.objects.all().order_by("-id")[0].id)
    isLast = (user.work_read[work_id - 1] == "4")

    context = {
        'work': work,
        'isLast': isLast,
        'user': user,
    }

    return HttpResponse(template.render(context, request))

'''汎用ビュー上では難しいか
class IndexView(DetailView):
    model = Work
    #model2 = User
    #work = get_object_or_404(Work, pk)
    form_class = CollectDataForm
    template_name = 'mkdata/sampleform.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # はじめに継承元のメソッドを呼び出す

        context['name'] = self.model.name
        #context['num_of_data'] = self.model.num_of_data
        #context['like'] = self.model.like
        #context['joy'] = self.model.joy
        #context['anger'] = self.model.anger
        #context['sadness'] = self.model.sadness
        #context['fun'] = self.model.fun
        #context['tech_constitution'] = self.model.tech_constitution
        #context['tech_story'] = self.model.tech_story
        #context['tech_character'] = self.model.tech_character
        #context['tech_speech'] = self.model.tech_speech
        #context['tech_picture'] = self.model.tech_picture

        return context

    #####
    #def get_form_kwargs(self):
    #    kwargs = super(IndexView, self).get_form_kwargs()
    #    kwargs['pk'] = self.model.id
    #    return kwargs
    #####


    #def get_success_url(self):
    #    return resolve_url('mkdata:vote', work_id=self.kwargs['pk'])


    #def form_valid(self, form):
    #    return super().form_valid(form)

'''


class ThanksView(TemplateView):
    template_name = "mkdata/thanks.html"


def vote(request, work_id):
    work = get_object_or_404(Work, pk=work_id)
    user = request.user

    ###まずはformの有効性判断&データ取得
    if work.genre == 1:
        evaluate_items = ('like', 'joy', 'anger', 'sadness', 'fun', "tech_constitution", "tech_story",
                          "tech_character", "tech_speech", "tech_picture")
    else:
        evaluate_items = ('like', 'joy', 'anger', 'sadness', 'fun', "tech_constitution", "tech_story",
                          "tech_character", "tech_speech", "tech_picture", 'tech_audio', 'tech_acting')

    evaluate_values = [0]*20

    for i in range(len(evaluate_items)):
        try:
            evaluate_values[i] = int(request.POST[evaluate_items[i]])###0-indexedに統一
        except:
            return HttpResponseRedirect(reverse('mkdata:index_again', args=(work_id,)))

    ###回答した事があるかどうか, あるならリセットのためにworkからその人分のデータ値を差し引く
    if user.work_evaluated is not None:
        if work_id in user.work_evaluated:
            index = user.work_evaluated.index(work_id)
            work.num_of_data -= 1

            if (user.evaluation_avg == []) or (user.evaluation_avg is None):
                user.evaluation_avg = [0]*20
                user.evaluation_std = [0]*20

            work.like -= user.work_evaluation[index][0]

            #print(user.evaluation_avg)

            if user.evaluation_std[1] != 0:
                work.joy -= (user.work_evaluation[index][1]-user.evaluation_avg[1])/user.evaluation_std[1]
                ###0の場合はどうせ足されている値も0なので考えなくて良い
            if user.evaluation_std[2] != 0:
                work.anger -= (user.work_evaluation[index][2]-user.evaluation_avg[2])/user.evaluation_std[2]
            if user.evaluation_std[3] != 0:
                work.sadness -= (user.work_evaluation[index][3]-user.evaluation_avg[3])/user.evaluation_std[3]
            if user.evaluation_std[4] != 0:
                work.fun -= (user.work_evaluation[index][4]-user.evaluation_avg[4])/user.evaluation_std[4]
            if user.evaluation_std[5] != 0:
                work.tech_constitution -= (user.work_evaluation[index][5]-user.evaluation_avg[5])/user.evaluation_std[5]
            if user.evaluation_std[6] != 0:
                work.tech_story -= (user.work_evaluation[index][6]-user.evaluation_avg[6])/user.evaluation_std[6]
            if user.evaluation_std[7] != 0:
                work.tech_character -= (user.work_evaluation[index][7]-user.evaluation_avg[7])/user.evaluation_std[7]
            if user.evaluation_std[8] != 0:
                work.tech_speech -= (user.work_evaluation[index][8]-user.evaluation_avg[8])/user.evaluation_std[8]
            if user.evaluation_std[9] != 0:
                work.tech_picture -= (user.work_evaluation[index][9]-user.evaluation_avg[9])/user.evaluation_std[9]

            if work.genre == 2:
                if user.evaluation_std[10] != 0:
                    work.mov_tech_audio -= (user.work_evaluation[index][10]-user.evaluation_avg[10])/user.evaluation_std[10]
                if user.evaluation_std[11] != 0:
                    work.mov_tech_acting -= (user.work_evaluation[index][11]-user.evaluation_avg[11])/user.evaluation_std[11]

            user.work_evaluation[index] = evaluate_values
        else:
            user.work_evaluated.append(work_id)
            user.work_evaluation.append(evaluate_values)
    else:
        user.work_evaluated = [work_id]
        user.work_evaluation = [evaluate_values]

    for i in range(len(user.work_evaluation)):
        user.work_evaluation[i] = user.work_evaluation[i]+[0]*(20-len(user.work_evaluation[i]))
    #print(user.work_evaluation)

    work.save()
    user.save()
    #print(user.work_evaluation)

    obj = user.work_like

    if len(obj) != 100000:
        obj = "".join(['0'] * 100000)

    obj = list(obj)
    obj[work_id - 1] = request.POST['like']

    user.work_like = "".join(obj)

    user.save()

    # if work.id >= Work.objects.all().order_by("-id")[0].id:
    if user.work_read[work_id - 1] == "4":
        user.data_entered = True
        user.save()
        ###recommend_sortを行う前に, userのデータを標準化, workモデルに反映
        user_standardize(user)
        recommendselect(request.user)
        return HttpResponseRedirect(reverse('mkdata:recommend', ))
    else:
        next = work.id + 1
        while next <= Work.objects.all().order_by("-id")[0].id:
            try:
                x = Work.objects.get(id=next)
            except Work.DoesNotExist:
                next += 1
                user.work_read[next - 1] = "0"
                user.save()
            else:
                if int(user.work_read[next-1]) >= 3:
                    break
                else:
                    next += 1

        return HttpResponseRedirect(reverse('mkdata:index', args=(next,)))

def SelectGenreView(request):
    user = request.user

    template = loader.get_template('mkdata/select_genre.html')

    context = {
        'user': user,
    }

    return HttpResponse(template.render(context, request))

def mkaddwork(request):
    addwork = AddedWork(genre=int(request.POST['genre']))
    addwork.name = request.POST['name']
    addwork.userid = request.user.id
    addwork.save()
    # print(addwork.name)
    # print(addwork.id)

    return HttpResponseRedirect(reverse('mkdata:freevote', args=(addwork.id,)))

class StartFreevoteView(CreateView):
    form_class = StartFreevoteForm
    template_name = 'mkdata/start_freevote.html'
    #success_url = reverse_lazy('cms:top')

    def form_valid(self, form):
        user = self.request.user
        addwork = form.save()
        self.object = addwork
        #messages.success(self.request, "保存しました")
        return HttpResponseRedirect(reverse('mkdata:freevote', args=(self.object.id,)))

    def form_invalid(self,form):
        #messages.warning(self.request, "保存できませんでした")

mkdata/templates/mkdata/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@CrossRecommender" />
    <meta property="og:url" content="http://crossrecommender-env.eba-p8hy6ngk.us-east-1.elasticbeanstalk.com/cms" />
    <meta property="og:title" content="Cross Recommender" />
    <meta property="og:description" content="新しいお気に入りを見つけよう" />
    <meta property="og:image" content="http://crossrecommender-env.eba-p8hy6ngk.us-east-1.elasticbeanstalk.com/static/images/CR.png" />
    <title>{% block title %}{% endblock %}Cross Recommender</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
    <!-- NAVIGATION BAR -->
    <header>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <!-- LOGO -->
                <a class="navbar-item" href="/cms">
                    <img src="{% static 'images/CRbig.svg' %}" width="40" height="150">
                </a>
                <!-- HAMBURGER MENU -->
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="my-menu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div class="navbar-menu" id="my-menu">
                <div class="navbar-end">
                    {% if user.is_authenticated %}
                    <!--#####added#####-->
                    <div class="buttons">
                        <a class="button is-info navbar-item" href="{% url 'cms:user_detail' user.pk %}"><strong>Detail</strong></a>
                        <!--<a class="navbar-item" href="{% url 'cms:user_detail' user.pk %}"><strong>Detail</strong></a>-->
                        <!--###############-->
                        <a class="button is-light navbar-item" href="{% url 'cms:guestdelete' %}">Log out</a>
                    </div>
                    {% else %}
                    <div class="buttons">
                        <a class="button is-info navbar-item" href="{% url 'cms:signup' %}"><strong>Sign up</strong></a>
                        <a class="button is-light navbar-item" href="{% url 'cms:login' %}"><strong>Log in</strong></a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    <!-- MESSAGE -->
    {% for field, errors in form.errors.items %}
        <article class="message is-warning">
            <div class="message-body">
            {% for error in errors %}
                <p><strong>{{ error }}</strong></p>
            {% endfor %}
            </div>
        </article>
    {% endfor %}
    <!-- MAIN -->
    <main>
        {% block hero %}{% endblock %}
        {% block tab %}{% endblock %}
        {% block content %}{% endblock %}
    </main>
    <!-- FOOTER -->
    <footer class="footer">
        <div class="container">
            <div class="content has-text-centered">
                <strong>Cross Recommender</strong>
            </div>
            <div class="content has-text-centered">
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSdib-ziaHUKaYxRFy5grGduBP7pvwLzNamHwjUIZ0tXOB-4xQ/viewform?usp=sf_link" class="has-text-danger">お問い合わせ、不具合の報告はこちら</a>
            </div>
            <div class="content has-text-centered">
                <a href="/cms/terms" class="has-text-danger">利用規約</a>
                &ensp; &ensp; &ensp;
                <a href="/cms/policy" class="has-text-danger">プライバシーポリシー</a>
            </div>
        </div>
    </footer>

    <!-- FOR JAVASCRIPT -->
    <script>
        <!-- FOR HAMBURGER MENU -->
        for (const burder of document.getElementsByClassName('navbar-burger')) {
            const menuId = burder.dataset.target;
            const menu = document.getElementById(menuId);
            burder.addEventListener('click', e => {
                burder.classList.toggle('is-active');
                menu.classList.toggle('is-active');
            });
        }
        {% block extrajs %}{% endblock %}
    </script>
</body>
</html>

mkdata/templates/mkdata/index.html
<html>
<body>
    <p>Hello, world!!</p>
</body>
</html>

mkdata/templates/mkdata/no_recommendation.html
{% extends 'mkdata/base.html' %}

{% block title %} レコメンド作品一覧 | Cross Recommender {% endblock %}

{% block hero %}
<section class="hero is-small is-link is-bold">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title">{{ user.username }}さんへのオススメ作品</h1>
            <h2 class="subtitle">Recommendation List</h2>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <p>データが入力されていないため, オススメ作品がありません。</p>
    <p>データ入力は<a href="/mkdata/start">こちら</a>から！</p>
</section>
{% endblock %}

mkdata/templates/mkdata/select_favorite_again.html
{% extends 'mkdata/base.html' %}

{% block title %} データ入力 | Cross Recommender {% endblock %}

{% block content %}
<main class="columns">
  <div class="column">

  </div>
</main>
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">データ入力</h1>
        <h2 class="subtitle is-6">Enter data</h2>
        <hr>
        <p class = "has-text-danger">5つの作品を選択してください。</p>
        <p>次に, {{ user.username }}さんが読んだこと・観たことがある作品の中で特に好きだったもの5つを選んでください。</p>
        <form method="post" action="{% url 'mkdata:userselected' %}">
            {% csrf_token %}
            <br>

            {% for work in read_works %}
                <label class="checkbox">
                    <input type="checkbox" name = "isSelected" value = "{{ work.id }}">
                        {{ work.name }}
                    <br>
                    <br>
                </label>
                <br>
            {% endfor %}

            <div class="field">
                <p class="control">
                    <input type="submit" value="次へ" class="button is-success">
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

mkdata/templates/mkdata/select_genre.html
{% extends 'mkdata/base.html' %}

{% block title %} データ入力 - 自由入力 | Cross Recommender{% endblock %}

{% block content %}

<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">データ入力（自由入力）</h1>
        <h2 class="subtitle is-6">Free Review</h2>
        <hr>
        <p>{{ user.username }}さんのおすすめの漫画, 映画について{{ user.username }}さんの評価を教えてください。</p>
        <p>まず, 入力する作品のジャンルと名前を入力してください。</p>

        <form method="post" action="{% url 'mkdata:mkaddwork'%}">
            {% csrf_token %}
            <div class="field">
                <label class="label">ジャンル</label>
                <div class="control">
                  <label class="radio">
                    <input type="radio" name="genre" value = 1>
                    漫画
                  </label>
                  <label class="radio">
                    <input type="radio" name="genre" value = 2>
                    映画
                  </label>
                </div>
            </div>
            <div class="field">
                <label class="label">作品名</label>
                <div class="control">
                    <input class="input" type="text" name ="name" placeholder="作品名を入力してください。">
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="次へ" class="button is-success">
                </p>
            </div>

        </form>
    </div>
</section>
{% endblock %}

mkdata/templates/mkdata/start_mkdata.html
{% extends 'mkdata/base.html' %}

{% block title %} データ入力 | Cross Recommender {% endblock %}

{% block content %}
<main class="columns">
  <div class="column">

  </div>
</main>
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">データ入力</h1>
        <h2 class="subtitle is-6">Enter data</h2>
        <hr>
        <p>ここでは, {{ user.username }}さんにオススメな作品をご紹介するために, {{ user.username }}さんが読んだことがある漫画・邦画について入力していただきます。</p>
        <p>まずは, 以下の中から{{ user.username }}さんが触れたことがある漫画・邦画<b>全てに</b>チェックをつけてください。</p>
        <p><strong><font color = "red">この一覧のうち、{{ user.username }}さんが触れたことのない作品からおすすめされますので、全ての作品に触れたことがある場合おすすめ作品が表示されません。ご注意ください。</font></strong></p>
        <form method="post" action="{% url 'mkdata:userread'%}">
            {% csrf_token %}
            <br>

            <h2 class="subtitle is-6"><b>漫画</b></h2>
            {% for comic in comics %}
                <label class="checkbox">
                    <input type="checkbox" name = "isRead" value = "{{ comic.id }}">
                        {{ comic.name }}
                    <br>
                    <br>
                </label>
                <br>
            {% endfor %}
            <h2 class="subtitle is-6"><b>邦画</b></h2>
            {% for jp_movie in jp_movies %}
                <label class="checkbox">
                    <input type="checkbox" name = "isRead" value = "{{ jp_movie.id }}">
                        {{ jp_movie.name }}
                    <br>
                    <br>
                </label>
                <br>
            {% endfor %}
            <div class="field">
                <p class="control">
                    <input type="submit" value="次へ" class="button is-success">
                </p>
            </div>
        </form>
    </div>
    <br>
    <div class="container is-mobile">
        <p>上記作品に読んだことのある漫画も見たことがある映画もない方は、申し訳ありませんが下記ページより作品名をご自分で入力して評価してください。</p>
        <a href="{% url 'mkdata:startfreevote' %}" class="button is-light is-small">自由入力はこちら</a>
    </div>
</section>
{% endblock %}

mkdata/templates/mkdata/start_survey.html
{% extends 'mkdata/base.html' %}

{% block title %} アンケート | Cross Recommender {% endblock %}

{% block content %}
<main class="columns">
  <div class="column">

  </div>
</main>
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">サービス開発のためのアンケート</h1>
        <h2 class="subtitle is-6">Enter data</h2>
        <hr>
        <p>ここでは, サービス開発のため, 見たことのある邦画について入力していただきます。</p>
        <p>まずは, 以下の中から見たことがある邦画にチェックをつけてください。</p>
        <form method="post" action="{% url 'mkdata:userread'%}">
            <!--ここのリンク先も後で変える-->
            {% csrf_token %}
            <br>
            <h2 class="subtitle is-6"><b>邦画</b></h2>
            {% for jp_movie in jp_movies %}
                <label class="checkbox">
                    <input type="checkbox" name = "isRead" value = "{{ jp_movie.id }}">
                        {{ jp_movie.name }}
                    <br>
                    <br>
                </label>
                <br>
            {% endfor %}
            <div class="field">
                <p class="control">
                    <input type="submit" value="次へ" class="button is-success">
                </p>
            </div>
        </form>
    </div>
    <br>
    <div class="container is-mobile">
        <p>上記作品に見たことがある映画がない方は、申し訳ありませんが下記ページより作品名をご自分で入力して評価してください。</p>
        <a href="{% url 'mkdata:selectgenre' %}" class="button is-light is-small">自由入力はこちら</a>
        <!--上のリンク先を直す-->
    </div>
</section>
{% endblock %}

mkdata/templates/mkdata/thanks.html
{% extends 'mkdata/base.html' %}

{% block title %} データ入力完了 - {{ work.name }} | Cross Recommender{% endblock %}

{% block content %}
    <section class="section">
        <h1 class="title is-4">データ入力終了</h1>
        <a href="{% url 'mkdata:recommend' %}" class="button is-success is-small">オススメ作品をチェック！</a>
        <a href="{% url 'mkdata:startfreevote'%}" class="button is-light is-small">自由入力をもう一回</a>
    </section>
{% endblock %}