cms/urls.py
from django.urls import path

from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    ###試しにBeforeTopViewを実装しました。必要ならすぐ消します
    #path('genuine/', views.TopView.as_view(), name='genuine_top'),
    #path('', views.BeforeTopView, name='top'),
    ###
    path('infomation/', views.InfomationView.as_view(), name='infomation'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('guestdelete/', views.GuestDelete, name='guestdelete'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signupagain/', views.UserCreateAgain.as_view(), name='signupagain'),
    path('guest/', views.GuestCreate.as_view(), name='guest'),
    path('guestagain/', views.GuestCreateAgain.as_view(), name='guestagain'),
    #path('guesttorealuser/', views.GuestToRealUser.as_view(), name='guestupdate'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), #追加
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'), #追加
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    #path('user/', views.UserList.as_view(), name='user_list'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user_delete'),
    #path('user/<int:pk>/recommend/', views.RecommendView.as_view(), name='user_recommend'),
    #path('works/<int:pk>/', views.WorksView.as_view(), name='works'),
    #path('works/', views.WorksList.as_view(), name='works_list'),
]

mkdata/urls.py
from django.urls import path

from . import views

app_name = 'mkdata'
###urls.pyにもapp_nameをつけてる

urlpatterns = [
    #path('<int:pk>/', views.IndexView.as_view(), name='index'),
    path('<int:work_id>/', views.IndexView, name='index'),
    path('<int:work_id>/again/', views.IndexAgainView, name='index_again'),
    path('<int:work_id>/vote/', views.vote, name='vote'),
    #path('selectgenre/', views.SelectGenreView, name='selectgenre'),
    path('startfreevote/', views.StartFreevoteView.as_view(), name='startfreevote'),
    path('mkaddwork/', views.mkaddwork, name='mkaddwork'),
    path('freevote/<int:pk>/', views.AddWorkView.as_view(), name='freevote'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    #path('<int:work_id>/recommend/', views.recommend, name='recommend'),
    path('recommend/', views.recommend, name='recommend'),
    #path('detail/', views.detail,name='detail'),
    path('start/',views.StartView, name='start'),
    path('userread/',views.UserRead, name='userread'),
    path('selectfavorite/', views.SelectFavoriteView, name='selectfavorite'),
    path('selectfavoriteagain/', views.SelectFavoriteAgainView, name='selectfavoriteagain'),
    path('userselected/', views.UserSelected, name='userselected'),
    path('haveread/<int:work_id>/', views.HaveRead, name='haveread'),
    #path('startSurvey/', views.StartSurveyView, name="startSurvey"),
    #path('usersee/', views.UserSee, name='usersee')
    #path('upload/', views.upload, name='upload'),
]

cms/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django import forms
import random, string

UserModel = get_user_model()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs['class'] = 'input'
       self.fields['password'].widget.attrs['class'] = 'input'

class UserCreateForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class GuestCreateForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2', 'tmppass')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        Q = randomname(random.randint(15,25))
        mail = randomname(random.randint(10,14))+'@cross.con'
        self.fields['password1'].initial = Q
        self.fields['password2'].initial = Q
        self.fields['password1'].widget.render_value = True
        self.fields['password2'].widget.render_value = True
        self.fields['tmppass'].initial = Q
        self.fields['tmppass'].widget.render_value = True
        self.fields['email'].initial = mail
        self.fields['email'].widget.render_value = True
        self.fields['email'].widget = forms.HiddenInput()
        self.fields['tmppass'].widget = forms.HiddenInput()
        self.fields['password1'].widget = forms.HiddenInput()
        self.fields['password2'].widget = forms.HiddenInput()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

'''
class GuestToRealUserForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'
'''

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        """
        print(self.user.tmppass)
        self.fields['old_password'].initial = self.user.tmppass
        self.fields['old_password'].widget.render_value = True
        #self.fields['old_password'].widget = forms.HiddenInput()
        """
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email','twitter')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'


def randomname(n):
   return ''.join(random.choices(string.ascii_letters + string.digits, k=n))

cms/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.


from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
)
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import (
    CreateView, UpdateView,DeleteView,
)

from .mixins import OnlyYouMixin
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, GuestCreateForm
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from mkdata import models as mkdata_models

from django.urls import reverse

from django.contrib.auth.mixins import LoginRequiredMixin


UserModel = get_user_model()

'''
def BeforeTopView(request):
    user = request.user
    if user.is_authenticated == False:
        return HttpResponseRedirect(reverse('cms:genuine_top', ))
    elif user.is_guest == True:
        return HttpResponseRedirect(reverse('cms:guestdelete', ))
    else:
        return HttpResponseRedirect(reverse('cms:genuine_top', ))
'''

class TopView(TemplateView):
    template_name = 'cms/top.html'

    '''
    def post(self, request, *args, **kwargs):
        user = self.request.user
        if user.is_guest:
            user.delete()
    '''


class InfomationView(TemplateView):
    template_name = 'cms/infomation.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'cms/login.html'

class Logout(LogoutView):
    template_name = 'cms/top.html'

def GuestDelete(request):
    user = request.user
    print(user)
    if user.is_authenticated == False:
        return HttpResponseRedirect(reverse('cms:top', ))
    if user.is_guest == True:
        user.delete()
        return HttpResponseRedirect(reverse('cms:top', ))
    else:
        return HttpResponseRedirect(reverse('cms:logout', ))



class UserCreate(CreateView):
    form_class = UserCreateForm
    template_name = 'cms/signup.html'
    success_url = reverse_lazy('cms:top')

    def form_valid(self, form):
        if not self.request.POST.getlist('isOK'):
            return HttpResponseRedirect(reverse('cms:signupagain', ))
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

class UserCreateAgain(CreateView):
    form_class = UserCreateForm
    template_name = 'cms/signupagain.html'
    success_url = reverse_lazy('cms:top')

    def form_valid(self, form):
        if not self.request.POST.getlist('isOK'):
            return HttpResponseRedirect(reverse('cms:signupagain', ))
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

class GuestCreate(CreateView):
    form_class = GuestCreateForm
    template_name = 'cms/guest.html'
    success_url = reverse_lazy('mkdata:start')

    def form_valid(self, form):
        if not self.request.POST.getlist('isOK'):
            return HttpResponseRedirect(reverse('cms:guestagain', ))
        user = form.save()
        login(self.request, user)
        user.is_guest = True
        user.save()
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

class GuestCreateAgain(CreateView):
    form_class = GuestCreateForm
    template_name = 'cms/guestagain.html'
    success_url = reverse_lazy('mkdata:start')

    def form_valid(self, form):
        if not self.request.POST.getlist('isOK'):
            return HttpResponseRedirect(reverse('cms:guestagain', ))
        user = form.save()
        login(self.request, user)
        user.is_guest = True
        user.save()
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

'''
class GuestToRealUser(UpdateView):
    model = UserModel
    form_class = GuestToRealUserForm
    template_name = 'cms/guest_password_change.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])
'''

class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    """パスワード変更ビュー"""
    success_url = reverse_lazy('cms:password_change_done')
    template_name = 'cms/password_change.html'
    def form_valid(self, form):
        super(PasswordChange, self).form_valid(form)
        self.request.user.tmppass = None
        self.request.user.is_guest = False
        self.request.user.save()
        return HttpResponseRedirect(self.get_success_url())


class PasswordChangeDone(LoginRequiredMixin,PasswordChangeDoneView):
    """パスワード変更完了"""
    template_name = 'cms/password_change_done.html'


class UserUpdate(OnlyYouMixin, UpdateView):
    model = UserModel
    form_class = UserUpdateForm
    template_name = 'cms/user_update.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])

class UserDetail(DetailView):
    model = UserModel
    template_name = 'cms/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

class UserList(ListView):
    model = UserModel
    template_name = 'cms/user_list.html'

class UserDelete(OnlyYouMixin, DeleteView):
    model = UserModel
    template_name = 'cms/user_delete.html'
    success_url = reverse_lazy('cms:top')

"""
class RecommendView(ListView):
    model = UserModel
    template_name = 'cms/user_recommend.html'

"""
class RecommendView(DetailView):
    model = UserModel
    template_name = 'cms/user_recommend.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        user = context['object']
        context['recommends'] = mkdata_models.mkbaseWorks(user.work_like)
        return context

class WorksView(DetailView): #作品紹介をみるためのページ用
    model = mkdata_models.Work
    template_name = "cms/works.html"

class WorksList(ListView):
    model = mkdata_models.Work
    template_name = "cms/works_list.html"

class TermsView(TemplateView):
    template_name = "cms/terms.html"

class PolicyView(TemplateView):
    template_name = 'cms/policy.html'

cms/templates/cms/guest.html
{% extends 'cms/base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ゲスト入場</h1>
        <h2 class="subtitle is-6">Guest Create</h2>
        <hr>
        <p class="help">アカウントをお持ちの方へ：ログインは<a href="{% url 'cms:login' %}">こちら</a></p>
        <p class="has-text-danger">ログアウトと同時にゲストアカウントは削除されます。</p>
        <p class="has-text-danger">正規アカウントをご希望の方は画面上部のボタンよりSign upしてください</p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
                    {{ form.email }}
                    {{ form.password1 }}
                    {{ form.password2 }}
                    {{ form.tmppass }}
            <br>
            <div class ="field">
                <label class="checkbox">
                    <input type="checkbox" name = "isOK" value = "OK">
                        <a href="/cms/terms">利用規約</a>に同意します
                    <br>
                    <br>
                </label>
                <br>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="登録" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/guest_password_change_done.html
{% extends "cms/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

cms/templates/cms/guestagain.html
{% extends 'cms/base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ゲスト入場</h1>
        <h2 class="subtitle is-6">Guest Create</h2>
        <hr>
        <p class="help">アカウントをお持ちの方へ：ログインは<a href="{% url 'cms:login' %}">こちら</a></p>
        <p class="has-text-danger">乱数長の乱数文字列によるパスワードとemailを作成します。</p>
        <br>
        <div class="container is-mobile">
        <p class="has-text-danger">アカウントの作成には利用規約への同意が必須です。</p>
        </div>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
                    {{ form.email }}
                    {{ form.password1 }}
                    {{ form.password2 }}
                    {{ form.tmppass }}
            <br>
            <div class ="field">
                <label class="checkbox">
                    <input type="checkbox" name = "isOK" value = "OK">
                        <a href="/cms/terms">利用規約</a>に同意します
                    <br>
                    <br>
                </label>
                <br>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="登録" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/login.html
{% extends 'cms/base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ログイン</h1>
        <h2 class="subtitle is-6">Login</h2>
        <hr>
        <p class="help">アカウントをお持ちでない方へ：サインアップは<a href="{% url 'cms:signup' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="ログイン" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/password_change_done.html
{% extends "cms/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'cms:top' %}">トップへ</a>
</p>
{% endblock %}

cms/templates/cms/signup.html
{% extends 'cms/base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">サインアップ</h1>
        <h2 class="subtitle is-6">Sign up</h2>
        <hr>
        <p class="help">アカウントをお持ちの方へ：ログインは<a href="{% url 'cms:login' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password1 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード（確認）</label>
                <div class="control has-icons-left">
                    {{ form.password2 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <br>
            <div class ="field">
                <label class="checkbox">
                    <input type="checkbox" name = "isOK" value = "OK">
                        <a href="/cms/terms">利用規約</a>に同意します
                    <br>
                    <br>
                </label>
                <br>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="登録" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/top.html
{% extends 'cms/base.html' %}

{% block title %}Home | {% endblock %}

{% block hero %}
<section class="hero is-large is-info" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.7)), url('https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80')"><!--修正-->
  <div class="hero-body">
        <div class="container">
            <h1 class="title">Cross Recommender</h1>
            <h2 class="subtitle">新しいお気に入りを見つけよう</h2>
            <!--educate用-->
            <!--
            <h2 class="subtitle has-text-danger">このページは移動しました。</h2>
            <h2>新ページ: <a href = "http://crossrecommender-env.eba-p8hy6ngk.us-east-1.elasticbeanstalk.com/cms">http://crossrecommender-env.eba-p8hy6ngk.us-east-1.elasticbeanstalk.com/cms</a></h2>
            <br>
            -->
            <!--ここまで-->
            <a href="/cms/infomation">
                <button class="button is-info is-inverted is-outlined">
                    <strong>More Info</strong>
                </button>
            </a>
            {% if user.is_authenticated %}
            <a href="/mkdata/start">
                <button class="button is-info is-inverted is-outlined">
                    <strong>データ入力はこちら</strong>
                </button>
            </a>
            {% else %}
            <a href="/cms/login">
                <button class="button is-info is-inverted is-outlined">
                    <strong>Login</strong>
                </button>
            </a>
            {% endif %}
        </div>
        <!--
        <div class="container">
            <br>
            <a href="https://forms.gle/76CfeAkMs4fiAN3GA" target="_blank">
                <button class="button is-info is-inverted is-outlined">
                    <strong>邦画作品のデータ入力ご協力のお願い</strong>
                </button>
            </a>
        </div>
        -->
        {% if user.is_authenticated %}
        <div class="container">
            <br>
            <a href="/mkdata/recommend">
                <button class="button is-info is-inverted is-outlined">
                    <strong>おすすめ作品一覧</strong>
                </button>
            </a>
        </div>
            {% if user.is_guest %}
            <br>
            <div class="container has-text-danger">
            ゲストログイン中です。<a href="/cms/password_change" class="has-text-info">こちら</a>からパスワードを設定してください。現在ログアウト後の再ログインができない状態です。
            </div>
            {% endif %}
        {% else %}
        <div class="container">
            <br>
            <a href="/cms/guest">
                <button class="button is-info is-inverted is-outlined">
                    <strong>ゲストアカウント作成</strong>
                </button>
            </a>
            <p>メールアドレス、パスワードの設定なしでご利用いただけます。</p>
        </div>
        <div class="container">
            <br>
            <a href="/cms/signup">
                <button class="button is-success is-inverted is-outlined">
                    <strong>Sign Up</strong>
                </button>
            </a>
            <p>正規アカウントを作成する場合はこちら。</p>
        </div>
        {% endif %}
        <!--
        <div class="container">
            {% if not user.is_authenticated %}
            <br>
            <a href="/cms/guest">
                <button class="button is-info is-inverted is-outlined">
                    <strong>ゲスト入場口</strong>
                </button>
            </a>
            {% endif %}
        </div>
        -->
    </div>
</section>
{% endblock %}


{% block content %}
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title">あなたの休日に、もう一つ楽しみを。</h1>
            <p>外出自粛や働き方改革で、以前より自宅にいる時間が長くなった現代。ふと新しい趣味を探そうと思って漫画や映画を探しても、
            作品やサービスが溢れかえっている今、それらの中から自分に最もあっているものを探し出すのは難しいですよね。そんなとき、
                Cross Recommenderは、あなたが最も楽しめる作品を探すのをお手伝いします。</p>
        </div>
    </div>
</section>
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title">あなたの好きな作品と似た傾向の作品をおすすめ</h1>
            <p>あなたが好きな作品と、他のユーザーのデータを照らし合わせ、あなたが好きな作品と似ている作品、
            あなたが好きな作品を同様に好きな人が面白いと感じている他の作品をお教えします。</p>
            {% if user.is_authenticated %}
            <p>データ入力は<a href = "/mkdata/start">こちら</a>から。</p>
            {% else %}
            <p>ログインは<a href="{% url 'cms:login' %}">こちら</a>から。</p>
            {% endif %}

        </div>
    </div>
</section>
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title">NEWS</h1>
        </div>
        <br>
        <div class="has-text-left">
            <ul>
                <li>2020.05.29　version 0.1をリリース。</li>
                <li>2020.06.06　version 0.2をリリース。レコメンドできる作品数が大幅に増加しました！</li>
                <li>2020.06.08　version 0.3をリリース。レコメンドできる作品数がさらに増加し, 120作品に。さらに, レコメンド精度が大幅アップ！</li>
                <li>2020.06.09　version 1.0をリリース。ついに邦画作品のレコメンド&データ入力が解禁！</li>
                <li>2020.06.10　version 1.1をリリース。面倒なユーザー登録なく、ゲストとしてサービスが利用できるようになりました！</li>
            </ul>
        </div>
    </div>
</section>

<!--educate用-->
<!--
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title has-text-danger">このページは移動しました</h1>
            <p>現在こちらのページは更新されていません。</p>
            <p><a href = "http://crossrecommender-env.eba-p8hy6ngk.us-east-1.elasticbeanstalk.com/cms">こちら</a>をご利用ください。</p>
            <p>（新規ユーザー登録をお願いします）</p>
        </div>
    </div>
</section>
-->
{% endblock %}

cms/templates/cms/user_detail.html
{% extends 'cms/base.html' %}
{% block title %}{{ request.user.last_name }} {{ request.user.first_name }} | {% endblock %}

{% block hero %}
<section class="hero is-link is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="media">
                <div class="media-content">
                    <h1 class="title">
                        {{ request.user.username }}
                    </h1>
                    {% if request.user.is_guest %}
                    <a href="{% url 'cms:password_change' %}">
                        <button class="button is-small is-danger is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>正規ユーザになる</strong>
                        </button>
                    </a>

                    {% else %}
                    <a href="{% url 'cms:user_update' request.user.pk %}">
                        <button class="button is-small is-info is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>プロフィールを追加する</strong>
                        </button>
                    </a>
                    <a href="{% url 'cms:user_delete' request.user.pk %}">
                        <button class="button is-small is-danger is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>アカウントを削除する</strong>
                        </button>
                    </a>
                    <a href="{% url 'cms:password_change' %}">
                        <button class="button is-small is-danger is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>パスワードを変更する</strong>
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="level">
            <div class="level-left">
                {% if request.user.twitter %}
                <div class="level-item">
                    <div class="tags has-addons">
                        <span class="tag"><span class="icon is-small is-left"><i class="fab fa-twitter"></i></span></span>
                        <span class="tag is-dark"><a class="has-text-white" href="https://twitter.com/{{ request.user.twitter }}" target="_blank">@{{ request.user.twitter }}</a></span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

cms/templates/cms/works.html
{% extends 'cms/base.html' %}

{% block title %}{{ work.name }}| {% endblock %}

{% block hero %}
<section class="hero is-link is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64 is-left">
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    </figure>
                </div>
                <div class="media-content">
                    <h1 class="title">
                        {{ work.name }}
                    </h1>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="level">
            <div class="level-left">
                {{ work.name }}についてのアンケートは<a href="{% url 'mkdata:index' work.pk %}">こちら</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}